/**
 * 301 map from the current production site (edusofthealth.com, PHP) to the
 * new routes, so existing search rankings and inbound links carry over.
 */
module.exports = {
  '/index.php': '/',
  '/about-us.php': '/about',
  '/contact-us.php': '/contact',
  '/become-a-partner.php': '/contact?type=partnerships',
  '/career.php': '/careers',
  '/news.php': '/news',
  '/blog.php': '/news',
  '/services.php': '/services',
  '/gem-approved.php': '/about#compliance',
  '/privacy-policy.php': '/privacy',
  '/terms-and-condition.php': '/terms',
  '/cookie-policy.php': '/cookies',

  '/products.php': '/portfolio',
  '/xray-machine.php': '/portfolio',
  '/buy-portable-x-ray-machine.php': '/portfolio?category=mobile-xray',
  '/handheld-portable-x-raysolutions.php': '/portfolio?category=handheld-xray',
  '/mobile-x-ray-solutions.php': '/portfolio?category=mobile-xray',
  '/fixed-x-ray-solutions.php': '/portfolio?category=fixed-xray',
  '/surgical-c-arms.php': '/portfolio?category=c-arms',
  '/dr-systems.php': '/portfolio?category=dr-detectors',
  '/cr-systems.php': '/portfolio?category=cr-systems',
  '/laser-x-ray-printer.php': '/portfolio?category=printers',
  '/x-ray-films.php': '/portfolio?category=films-media',
  '/ultrasound-thermal-paper.php': '/portfolio?category=accessories',
  '/it-solution.php': '/portfolio?category=software-ai',
  '/eye-auto-refractometer.php': '/portfolio?category=specialty',

  '/ultra-portable-handheld-x-ray-3ma.php': '/portfolio/eray-smart-3hs',
  '/ultra-portable-handheld-x-ray-5hs.php': '/portfolio/eray-smart-5hs',
  '/ultra-portable-handheld-x-ray-6hs.php': '/portfolio/eray-smart-6hs',
  '/portable-x-ray-machines.php': '/portfolio/eray-smart-t-series',
  '/digital-portable-x-ray-machines.php': '/portfolio/eray-smart-integrated',
  '/2kw-portable-x-ray.php': '/portfolio/eray-2kw-portable',
  '/40kw-digital-mobile-portable-x-ray.php': '/portfolio/eray-40kw-digital-mobile',
  '/50kw-motorized-digital-mobile-x-ray.php': '/portfolio/eray-50kw-motorized-mobile',
  '/fixed-x-ray-machine.php': '/portfolio/eray-rad-series',
  '/digital-x-ray-machine.php': '/portfolio/eray-smart-eco-dr',
  '/ceiling-free-x-ray.php': '/portfolio/eray-ceiling-free',
  '/ceiling-suspended-digital-radiography-solutions.php': '/portfolio/eray-ceiling-suspended-dr',
  '/eco-digital-mobile-c-arm.php': '/portfolio/eray-smart-5c-premium',
  '/c-arm-flat-panel-premium-rotatory.php': '/portfolio/eray-smart-5c-gold',
  '/premium-c-arm-rotataory-3030.php': '/portfolio/eray-smart-5c-premium-pro',
  '/eray-gold-flat-panel-detector.php': '/portfolio/eray-gold-100',
  '/eray-gold-breakfire.php': '/portfolio/eray-gold-breakfree',
  '/eray-igzo-flat-panel-detector.php': '/portfolio/eray-igzo',
  '/trimax-dr-system.php': '/portfolio/trimax-dr',
  '/trimax-cr-systems.php': '/portfolio/trimax-cr',
  '/eray-fire-cr-spark.php': '/portfolio/eray-firecr-spark',
  '/trimax-laser-imaging-printer.php': '/portfolio?category=printers',
  '/trimax-tx40-laser-imager.php': '/portfolio/trimax-tx40',
  '/trimax-tx55-laser-imager.php': '/portfolio/trimax-tx55',
  '/trimax-tx65-laser-imager.php': '/portfolio/trimax-tx65',
  '/thermal-printer.php': '/portfolio/eray-thermal-printer',
  '/espon-inkjet-printer.php': '/portfolio/eray-inkjet-printer',
  '/trimax-digital-x-ray-films.php': '/portfolio/trimax-digital-films',
  '/eray-medical-xray-film.php': '/portfolio/eray-medical-films',
  '/sony-ultrasound-rolls-type1.php': '/portfolio/sony-upp-110s',
  '/sony-ultrasound-rolls-type5.php': '/portfolio/sony-upp-110hg',
  '/tables-accessories.php': '/portfolio/tables-accessories',
  '/mobile-eye-testing-machine.php': '/portfolio/ai-optics-vision-screener',
};
